name = "http-gate"
spin_version = "1"
authors = ["mike tang <daogangtang@gmail.com>"]
description = "This is the http gate of the openforum application"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "http-gate"
source = "target/wasm32-wasi/release/http_gate.wasm"
#environment = {REDIS_URL = "redis://127.0.0.1:6379"}
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
