spin_manifest_version = 2

[application]
authors = ["mike tang <daogangtang@gmail.com>"]
description = "http gate."
name = "http-gate"
version = "0.2.0"

[[trigger.http]]
route = "/"
component = "http-gate"

[component.http-gate]
source = "target/wasm32-wasi/release/http_gate.wasm"

[component.http-gate.build]
command = "cargo build --target wasm32-wasi --release"
# watch = ["src/**/*.rs", "Cargo.toml"]
